apiVersion: v1
kind: Service
metadata:
  name: vault
spec:
  clusterIP: 10.52.12.236
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: 35.204.197.145
  ports:
    - name: vault-port
      nodePort: 31763
      port: 443
      protocol: TCP
      targetPort: 8200
  selector:
    app: vault
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  labels:
    app: vault
spec:
  serviceName: vault
  selector:
    matchLabels:
      app: vault
  replicas: 2
  template:
    metadata:
      labels:
        app: vault
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - vault
              topologyKey: kubernetes.io/hostname
      initContainers:
        - name: config
          image: busybox
          env:
            - name: GCS_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: vault
                  key: gcs_bucket_name
          command: ["/bin/sh", "-c"]
          args:
            - |
              cat > /etc/vault/config/vault.hcl <<EOF
              listener "tcp" {
                address = "0.0.0.0:8200"
                tls_cert_file = "/etc/vault/tls/vault.crt"
                tls_key_file = "/etc/vault/tls/vault.key"
                tls_min_version = "tls12"
              }

              storage "gcs" {
                bucket = "${GCS_BUCKET_NAME}"
                ha_enabled = "true"
              }

              ui = true
              EOF

          volumeMounts:
            - name: vault-config
              mountPath: /etc/vault/config
      containers:
        - name: vault-init
          image: gcr.io/hightowerlabs/vault-init
          imagePullPolicy: Always
          env:
            - name: CHECK_INTERVAL
              value: "10"
            - name: GCS_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: vault
                  key: gcs_bucket_name
            - name: KMS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  name: vault
                  key: kms_key_id
        - name: vault
          image: "vault:0.11.4"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            # Used by Vault as redirect address
            - name: VAULT_API_ADDR
              valueFrom:
                configMapKeyRef:
                  name: vault
                  key: api_addr
            - name: VAULT_CLUSTER_ADDR
              value: "https://$(POD_IP):8201"
          args:
            - "server"
            - "-config=/etc/vault/config/vault.hcl"
          ports:
            - name: http
              containerPort: 8200
              protocol: TCP
            - name: server
              containerPort: 8201
              protocol: TCP
          readinessProbe:
            httpGet:
              path: "/v1/sys/health?standbyok=true"
              port: http
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: "100m"
              memory: "256Mi"
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          volumeMounts:
            - name: vault-config
              mountPath: /etc/vault/config
            - name: vault-tls
              mountPath: /etc/vault/tls
      volumes:
        - name: vault-config
          emptyDir: {}
        - name: vault-tls
          secret:
            secretName: vault-tls
